// import { getServerSession } from 'next-auth';
import Provider from '../context/provider';
import './global.css';
// import { authOptions } from './api/auth/[...nextauth]/route';

export const metadata = {
  title: 'Welcome to kg',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
